Nano/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# 正在部署的应用的名称
app_name = 'Nano'

urlpatterns = [
    path('', views.index, name='nano_index'),
    path('about/', views.about, name='nano_about'),
    path('project/', views.project, name='nano_project'),

    # mobileNet OD
    path('object-detection/', views.object_detection, name='object_detection'),
    path('main_interface/', views.main_interface, name='main_interface'),

    # yolov5s
    path('yolov5s/', views.yolov5s, name='yolov5s'),
    path('yolov5sOD/', views.yolov5sOD, name='yolov5sOD'),

    # 接收告警信息
    path('alert/', views.alert_data, name='alert_data'),

    # 输电线缺陷检测
    path('anomaly-detection/', views.anomaly_detection, name='anomaly_detection'),
]

api1602/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
# from Nano import views
from userprofile import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nano/', include('Nano.urls', namespace='nano')),
    # path('',views.index,name='index'),
    path('',views.user_login,name='user_login'),
    # 用户管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
]

#添加这行
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
]

userprofile/models.py
from django.db import models

# Create your models here.

userprofile/forms.py
# 引入表单类
from django import forms
# 引入 User 模型
from django.contrib.auth.models import User

# 登录表单，继承了 forms.Form 类
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from .forms import UserLoginForm
# 引入logout模块
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法数据
            data = user_login_form.cleaned_data
            # 检验账号、密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个 user 对象
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # 将用户数据保存在 session 中，即实现了登录动作
                login(request, user)
                return redirect("Nano:nano_index")
            else:
                return HttpResponse("账号或密码输入有误。请重新输入~")
        else:
            return HttpResponse("账号或密码输入不合法")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = { 'form': user_login_form }
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

# 用户退出
def user_logout(request):
    logout(request)
    return redirect("Nano:nano_index")

templates/userprofile/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>AI-Edge</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/modern-business.css' %} " rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}"/>

  <style>
    body {
    background-image: url('{% static 'images/bg.jpg' %}');
    /* background-size: 100%;
    background-repeat: no-repeat; */
    padding-top: 10rem;
    padding-bottom: calc(10rem - 4.5rem);
    background-position: center;
    background-repeat: no-repeat;
    background-attachment: scroll;
    background-size: cover;
    }
  </style>

</head>

<body>

  <!-- <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'nano:nano_index'%}">YNU-边缘智能Lab</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'nano:nano_about'%}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'nano:nano_project'%}">Project</a>
          </li>

          {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="http://localhost:9004/d/wqc48EuGz/anomaly_alert?orgId=1&from=1620251763372&to=1620273363372&viewPanel=2">System</a>
              </li>
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href='{% url "userprofile:logout" %}'>logout</a>
                  </div>
              </li>
          {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'userprofile:login' %}">login</a>
              </li>                    
          {% endif %}
        </ul>
      </div>
    </div>
  </nav> -->
  
  <div class="container"> 
    <div class="row">
      &nbsp
    </div>
    <div class="row">
      &nbsp
    </div>
    <div class="row">
      &nbsp
    </div>
    <div class="row">
      &nbsp
    </div>
    <div class="row">
      &nbsp
    </div>
    <div class="row">
      &nbsp
    </div>
    <div class="row">
      &nbsp
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-6 mb-4">
        <form method="post" action="." id="login_frame">
          <h4>输电线缺陷检测告警系统</h3>
          {% csrf_token %}
          <!-- 账号 -->
          <div class="form-group row">
            <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Name</label>
            <div class="col-sm-10">
              <input type="text" class="form-control form-control-lg" id="username" placeholder="Full Name" name="username">
            </div>
          </div>
          <!-- 密码 -->
          <div class="form-group row">
            <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Password</label>
            <div class="col-sm-10">
              <input type="password" class="form-control form-control-lg" id="password" placeholder="Password" name="password"> 
            </div>
          </div>
          <!-- 提交按钮 -->
          <button type="submit" class="btn btn-outline-primary" id="sendMessageButton">登录</button>
        </form>
      </div>
    </div>
    

    

    <!-- <div class="row">
      <div class="col-lg-4 mb-4">
        <h3> You Can Login Here </h3>
        <form method="post" action=".">
          {% csrf_token %}
          
          <div class="form-group">
              <label for="username">full name</label>
              <input type="text" class="form-control" id="username" name="username">
          </div>
          
          <div class="form-group">
              <label for="password">password</label>
              <input type="password" class="form-control" id="password" name="password">
          </div>
          
          <button type="submit" class="btn btn-primary" id="sendMessageButton">登录</button>
        </form>
      </div>
    </div> -->

  </div>

  <!-- Footer -->
  <!-- <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
  </footer> -->

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %} "></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>

</body>

</html>

templates/userprofile/login1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>AI-Edge</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/modern-business.css' %} " rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}"/>

</head>

<body>
    <div id="login_frame">
 
        <p id="image_logo"><img src="images/login/fly.png"></p>
     
        <form method="post" action=".">
            {% csrf_token %}
            <p><label class="label_input">用户名</label><input type="text" class="form-control" id="username" name="username"></p>
            <p><label class="label_input">密码</label><input type="password" class="form-control" id="password" name="password"></p>
     
            <div id="login_control">
                <button type="submit" class="btn btn-primary" id="sendMessageButton">Submit</button>
            </div>
        </form>
    </div>
  
    <div class="container"> 
        <div class="row">
        <div class="col-lg-8 mb-4">
            <h3> You Can Login Here </h3>
            <form method="post" action=".">
            {% csrf_token %}
            <!-- 账号 -->
            <div class="form-group">
                <label for="username">full name</label>
                <input type="text" class="form-control" id="username" name="username">
            </div>
            <!-- 密码 -->
            <div class="form-group">
                <label for="password">password</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
            <!-- 提交按钮 -->
            <button type="submit" class="btn btn-primary" id="sendMessageButton">Submit</button>
            </form>
        </div>
        </div>
    </div>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %} "></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>

</body>

</html>