Nano/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# 正在部署的应用的名称
app_name = 'Nano'

urlpatterns = [
    path('', views.index, name='nano_index'),
    path('about/', views.about, name='nano_about'),
    path('project/', views.project, name='nano_project'),

    # mobileNet OD
    path('object-detection/', views.object_detection, name='object_detection'),
    path('main_interface/', views.main_interface, name='main_interface'),

    # yolov5s
    path('yolov5s/', views.yolov5s, name='yolov5s'),
    path('yolov5sOD/', views.yolov5sOD, name='yolov5sOD'),

    # 接收告警信息
    path('alert/', views.alert_data, name='alert_data'),

    # 输电线缺陷检测
    path('anomaly-detection/', views.anomaly_detection, name='anomaly_detection'),
]

api1602/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
# from Nano import views
from userprofile import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nano/', include('Nano.urls', namespace='nano')),
    # path('',views.index,name='index'),
    path('',views.user_login,name='user_login'),
    # 用户管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
]

#添加这行
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
]

Nano/models.py
from django.db import models
# 导入内建的User模型。
from django.contrib.auth.models import User
# timezone 用于处理时间相关事务。
from django.utils import timezone
from PIL import Image
# 引入imagekit
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit
# dingtalk
from django.db import models

'''
表1 receiver(主键) dingding-webhook
表2 自增ID alertname instance anomaly_img startsAt receiver longitude latitude
'''

class Receiver(models.Model):
    receiver = models.CharField(max_length=30)
    receiver_num = models.IntegerField()
    dingtalk_robot_api = models.CharField(max_length=200)

    class Meta:
        db_table = 'receiver'
        unique_together = ('receiver', 'receiver_num')


class Alert(models.Model):
    id = models.AutoField(primary_key=True)
    alertname = models.CharField(max_length=100)
    instance = models.CharField(max_length=50)
    anomaly_img = models.URLField()
    startsAt = models.DateTimeField()
    receiver = models.CharField(max_length=30)
    longitude = models.CharField(max_length=30)
    latitude = models.CharField(max_length=30)

    class Meta:
        db_table = 'alert'

Nano/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import Alert

# Alert表单类
class AlertForm(forms.ModelForm):
    class Meta:
        model = Alert
        fields = ('alertname', 'instance', 'anomaly_img', 'startsAt', 'receiver', 'longitude', 'latitude')

Nano/views.py
from django.http import JsonResponse
from django.shortcuts import render
# 导入 HttpResponse 模块
from django.http import HttpResponse
from django.core.paginator import Paginator

#mobileNet od
from PIL import Image
import numpy as np
import base64
import io
import os
import json
from .tf_inference import load_model, inference
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
sess, detection_graph = load_model()

# alert
from .models import Alert
import re
from .forms import AlertForm

# yolov5s OD
import datetime
import shutil
from datetime import timedelta
from .AIDetector_pytorch import Detector
import core.main
import time
import cv2

# 访问首页
def index(request):
    # render函数：载入模板，并返回context对象
    return render(request, 'nano/index.html')

# 关于我们
def about(request):
    return render(request, 'nano/about.html')

# 查看项目
def project(request):
    return render(request, 'nano/portfolio-1-col.html')

# mobileNet OD
def object_detection(request):
    return render(request, 'nano/object_detection.html')

# mobileNet OD
def main_interface(request):
    if request.method == 'POST':
        print("yes")
        response = json.loads(request.body)
        data_str = response['image']
        print('data_str',type(data_str))
        point = data_str.find(',')
        base64_str = data_str[point:]  # remove unused part like this: "data:image/jpeg;base64,"

        image = base64.b64decode(base64_str)       
        img = Image.open(io.BytesIO(image))

        if(img.mode!='RGB'):
            img = img.convert("RGB")
        
        # convert to numpy array.
        img_arr = np.array(img)

        # do object detection in inference function.
        results = inference(sess, detection_graph, img_arr, conf_thresh=0.5)
        # print(results)
        # print(type(results))
        return HttpResponse(json.dumps(results))
    else:
        print("error")

# yolov5s OD for 输电线缺陷检测
def yolov5s(request):
    return render(request, 'nano/yolov5s.html')

# yolov5s OD for 输电线缺陷检测
def yolov5sOD(request):
    if request.method == 'POST':
        print("yes")
        response = json.loads(request.body)
        data_str = response['image']
        print('data_str',type(data_str))
        point = data_str.find(',')
        base64_str = data_str[point:]  # remove unused part like this: "data:image/jpeg;base64,"

        image = base64.b64decode(base64_str)       
        img = Image.open(io.BytesIO(image))

        if(img.mode!='RGB'):
            img = img.convert("RGB")
        
        # convert to numpy array.
        img_arr = np.array(img)
        print(type(img_arr))

        now = time.strftime("%Y-%m-%d-%H_%M_%S",time.localtime(time.time()))
        print('now:',now)
        src_path = now + r'.jpg'
        print("src_path:",src_path)
        cv2.imwrite(src_path, img_arr)
        shutil.copy(src_path,'static\ct')
        image_path = os.path.join('static\ct',now+r'.jpg')
        yolov5s = Detector()
        pid, image_info, pred_boxes = core.main.c_main(
            image_path, yolov5s, 'jpg')
        # print('pid:',pid)
        # print('image_info:',image_info)
        # print('pred_bboxs:',pred_boxes)
        results = pred_boxes
        return HttpResponse(json.dumps(results))
    else:
        print("error")

# 输电线缺陷检测
def anomaly_detection(request):
    return render(request, 'nano/anomaly_detection.html')


# 接收告警消息，写入数据库
def alert_data(request):
    if request.method == 'POST':
        # 将提交的数据赋值到表单实例
        alert_form = AlertForm(data=request.POST)
        # 判断数据是否满足模型要求
        if alert_form.is_valid():
            # 保存数据，但是暂时不提交
            new_alert = alert_form.save(commit=False)
            new_alert.save()
            print("Receive Alert, please be careful !!!")
            # print(new_alert['anomaly_img'])
            return HttpResponse("POST success")
        else:
            return HttpResponse("POST error")
    else:
        return HttpResponse("please use post")

templates/nano/anomaly_detection.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>AI-Edge</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/modern-business.css' %} " rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'nano:nano_index'%}">YNU-智能边缘Lab</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'nano:nano_project'%}">算法管理</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'nano:anomaly_detection'%}">实时视频</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://localhost:9004/d/wqc48EuGz/anomaly_alert?orgId=1&from=1620251763372&to=1620273363372&viewPanel=2">告警管理</a>
          </li>
          {% if user.is_authenticated %}
              <!-- 如果用户已经登录，则显示用户名下拉框 -->
              <!-- <li class="nav-item">
                <a class="nav-link" href="http://localhost:9004/d/wqc48EuGz/anomaly_alert?orgId=1&from=1620251763372&to=1620273363372&viewPanel=2">System</a>
              </li> -->
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href='{% url "userprofile:logout" %}'>登出</a>
                  </div>
              </li>
          <!-- 如果用户未登录，则显示 “登录” -->
          {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'userprofile:login' %}">登入</a>
              </li>                    
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <!-- <h1 class="mt-4 mb-3">Project
      <small>Subheading</small>
    </h1> -->

    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{% url 'nano:nano_index'%}">Home</a>
      </li>
      <li class="breadcrumb-item active">Portfolio 1</li>
    </ol>

    <!-- Project One -->
    <div class="row">
      <div class="col-md-7">
        <!-- <a href="#">
          <img class="img-fluid rounded mb-3 mb-md-0" src="{% static 'images/project-project1.png' %} " alt="">
        </a> -->
        <video class="img-fluid rounded mb-3 mb-md-0" controls="controls" autoplay="autoplay"  volume="1" id="myVideo"  loop="loop">
            <source src="https://cdn.ccy.icu/powerline_1.mp4" type="video/mp4"/>
        </video> 
      </div>
      <div class="col-md-5">
        <h3>输电线路缺陷检测</h3>
        <p>无人机协助的特高压输电线路缺陷检测.</p>
        <a class="btn btn-primary" href="#">View Project
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Project Two -->
    <div class="row">
        <div class="col-md-7">
          <!-- <a href="#">
            <img class="img-fluid rounded mb-3 mb-md-0" src="{% static 'images/project-project1.png' %} " alt="">
          </a> -->
          <video class="img-fluid rounded mb-3 mb-md-0" controls="controls" autoplay="autoplay"  volume="1" id="myVideo"  loop="loop">
              <source src="https://cdn.ccy.icu/demo.mp4" type="video/mp4"/>
          </video> 
        </div>
        <div class="col-md-5">
          <h3>输电线路缺陷检测</h3>
          <p>无人机协助的特高压输电线路缺陷检测.</p>
          <a class="btn btn-primary" href="#">View Project
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>
        </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Project Three -->
    <div class="row">
      <div class="col-md-7">
        <a href="#">
          <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/700x300" alt="">
        </a>
      </div>
      <div class="col-md-5">
        <h3>Project Three</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, temporibus, dolores, at, praesentium ut unde repudiandae voluptatum sit ab debitis suscipit fugiat natus velit excepturi amet commodi deleniti alias possimus!</p>
        <a class="btn btn-primary" href="#">View Project
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Project Four -->
    <div class="row">

      <div class="col-md-7">
        <a href="#">
          <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/700x300" alt="">
        </a>
      </div>
      <div class="col-md-5">
        <h3>Project Four</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, quidem, consectetur, officia rem officiis illum aliquam perspiciatis aspernatur quod modi hic nemo qui soluta aut eius fugit quam in suscipit?</p>
        <a class="btn btn-primary" href="#">View Project
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Pagination -->
    <ul class="pagination justify-content-center">
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">1</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">2</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">3</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    </ul>

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; https://ccy.icu 2021</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %} "></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>

</body>

</html>

templates/nano/object_detection.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI-Edge</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">
    <style>
      .jumbotron {
        background-color: #cae0f5;
      }
    </style>
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> -->
</head>

<body onresize="windowResized()">
  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'nano:nano_index'%}">YNU-智能边缘Lab</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'nano:nano_project'%}">算法管理</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'nano:anomaly_detection'%}">实时视频</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://localhost:9004/d/wqc48EuGz/anomaly_alert?orgId=1&from=1620251763372&to=1620273363372&viewPanel=2">告警管理</a>
          </li>
          {% if user.is_authenticated %}
              <!-- 如果用户已经登录，则显示用户名下拉框 -->
              <!-- <li class="nav-item">
                <a class="nav-link" href="http://localhost:9004/d/wqc48EuGz/anomaly_alert?orgId=1&from=1620251763372&to=1620273363372&viewPanel=2">System</a>
              </li> -->
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href='{% url "userprofile:logout" %}'>登出</a>
                  </div>
              </li>
          <!-- 如果用户未登录，则显示 “登录” -->
          {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'userprofile:login' %}">登入</a>
              </li>                    
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">名称  目标检测Demo</li>
          <li class="list-group-item">状态  模型已部署</li>
          <li class="list-group-item">调用次数    x次</li>
          <li class="list-group-item">描述  模型部署在后台</li>
          <li class="list-group-item">数据采集 xxxxxx</li>
        </ul>
      </div>
    </div>

    <h5 class='title' id='tips'> 
    <div id="container">
    <img src="{% static 'images/demo.jpg' %} " id="image" class="center">
    <div id="text-container">
      <p id="instruction" class="green-color">
      <button class="btn btn-primary" onClick="clickUploader()">上传图片</button>

      <p id="warning" class="result-color"></p>
      <p class="result-color">
        在下方显示结果
      </p>
      <input name="imgFile" type="file" id="fileUploader" accept="image/*" onChange="handleFiles()">
    </div>
    <canvas id="canvas"></canvas>
    </div>

  </div>

  <!-- Footer -->
  <div>
    <br><br><br>
  </div>
  <footer class="py-3 bg-light fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-dark">Copyright &copy; https://ccy.icu 2020</p>
    </div>
  </footer>
  <script src="{% static 'js/index.js' %} "></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/nano/portfolio-1-col.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>AI-Edge</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/modern-business.css' %} " rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'nano:nano_index'%}">YNU-智能边缘Lab</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'nano:nano_project'%}">算法管理</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'nano:anomaly_detection'%}">实时视频</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://localhost:9004/d/wqc48EuGz/anomaly_alert?orgId=1&from=1620251763372&to=1620273363372&viewPanel=2">告警管理</a>
          </li>
          {% if user.is_authenticated %}
              <!-- 如果用户已经登录，则显示用户名下拉框 -->
              <!-- <li class="nav-item">
                <a class="nav-link" href="http://localhost:9004/d/wqc48EuGz/anomaly_alert?orgId=1&from=1620251763372&to=1620273363372&viewPanel=2">System</a>
              </li> -->
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href='{% url "userprofile:logout" %}'>登出</a>
                  </div>
              </li>
          <!-- 如果用户未登录，则显示 “登录” -->
          {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'userprofile:login' %}">登入</a>
              </li>                    
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Project
      <small>Subheading</small>
    </h1>

    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{% url 'nano:nano_index'%}">Home</a>
      </li>
      <li class="breadcrumb-item active">Portfolio 1</li>
    </ol>

    <!-- Project One -->
    <div class="row">
      <div class="col-md-7">
        <a href="{% url 'nano:object_detection'%}">
          <img class="img-fluid rounded mb-3 mb-md-0" src="{% static 'images/index-project1.png' %} " alt="">
        </a>
      </div>
      <div class="col-md-5">
        <h3>目标检测Demo</h3>
        <p>基于mobilenet实现简单目标检测，模型部署在Django后端.</p>
        <a class="btn btn-primary" href="{% url 'nano:object_detection'%}">View Project
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Project Two -->
    <div class="row">
      <div class="col-md-7">
        <a href="{% url 'nano:yolov5s'%}">
          <img class="img-fluid rounded mb-3 mb-md-0" src="{% static 'images/index-project2.png' %}" alt="">
        </a>
      </div>
      <div class="col-md-5">
        <h3>基于yolov5s的输电线缺陷检测实例</h3>
        <p>基于yolo实现简单目标检测,模型部署在后端.</p>
        <a class="btn btn-primary" href="{% url 'nano:object_detection'%}">View Project
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Project Three -->
    <div class="row">
      <div class="col-md-7">
        <a href="#">
          <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/700x300" alt="">
        </a>
      </div>
      <div class="col-md-5">
        <h3>Project Three</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, temporibus, dolores, at, praesentium ut unde repudiandae voluptatum sit ab debitis suscipit fugiat natus velit excepturi amet commodi deleniti alias possimus!</p>
        <a class="btn btn-primary" href="#">View Project
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Project Four -->
    <div class="row">

      <div class="col-md-7">
        <a href="#">
          <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/700x300" alt="">
        </a>
      </div>
      <div class="col-md-5">
        <h3>Project Four</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, quidem, consectetur, officia rem officiis illum aliquam perspiciatis aspernatur quod modi hic nemo qui soluta aut eius fugit quam in suscipit?</p>
        <a class="btn btn-primary" href="#">View Project
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Pagination -->
    <ul class="pagination justify-content-center">
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">1</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">2</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">3</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    </ul>

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %} "></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>

</body>

</html>